### ISSUE TITLE
ImportError: No module named ssl_match_hostname on init

### ISSUE THREAD

**Issue by nlynn12** [datmo/datmo#289]
So I've tried to install Datmo but for my first test sadly I run into an error related to docker. Do you have a fix for this? I'm on Ubuntu 18.04.

```bash
datmo init
Traceback (most recent call last):
  File "/usr/local/bin/datmo", line 7, in <module>
    from datmo.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/datmo/__init__.py", line 9, in <module>
    from datmo.core.util.logger import DatmoLogger
  File "/usr/local/lib/python2.7/dist-packages/datmo/core/util/logger.py", line 9, in <module>
    from datmo.core.util.misc_functions import grep
  File "/usr/local/lib/python2.7/dist-packages/datmo/core/util/misc_functions.py", line 46, in <module>
    from datmo.core.controller.environment.driver.dockerenv import DockerEnvironmentDriver
  File "/usr/local/lib/python2.7/dist-packages/datmo/core/controller/environment/driver/dockerenv.py", line 26, in <module>
    from docker import DockerClient
  File "/usr/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .build import tar, exclude_paths
  File "/usr/lib/python2.7/dist-packages/docker/utils/build.py", line 5, in <module>
    from .utils import create_archive
  File "/usr/lib/python2.7/dist-packages/docker/utils/utils.py", line 18, in <module>
    from .. import tls
  File "/usr/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/usr/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/usr/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```

**Comment by nlynn12** [comment]
I've tried to reinstall docker-python, both via apt and via pip, but without luck.

**Comment by shabazpatel** [comment]
There seems to be an issue with the docker-python client. Can you try running following command as described [here](https://github.com/docker/docker-py/issues/1502#issuecomment-418346541) 
```
cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports
```
